# Generated by Django 4.2.2 on 2023-12-20 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
