# Generated by Django 4.2.2 on 2023-12-07 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsstory',
            old_name='image',
            new_name='image_url',
        ),
    ]
