# Generated by Django 4.2.2 on 2023-12-21 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_newsstory_options_newsstory_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='likes',
        ),
    ]
